### PR TITLE
Use LIBDIR instead of BINDIR

### PR DESCRIPTION
**Pull request by ops**
Fix for `make ldconfig`.

### CODE REVIEW

**Comment by spiro-trikaliotis** [comment]
Can you elabortate on this patch?
From a first look, it seems reasonable to me. However, as it has been unnoticed for so long, it seems not to cause any issues.

Or am I missing something?

**Comment by ops** [comment]
Maybe most systems have /usr/local/lib in path lib search path by default and nobody noticed this. My Solus Linux doesn't.

**Comment by spiro-trikaliotis** [comment]
Mine does not, but I did not notice the problem either. That's weird.

However, I merged your patch.

**Comment by ops** [comment]
Thanks. Related issue: Solus doesn't have `/etc/ld.so.conf.d` directory created by default so `make ldconfig` fails in that case too.

**Comment by spiro-trikaliotis** [comment]
But the directory is the same, so /etc/ld.so.conf.d has to be created?
In this case, I would accept a PR. :)

**Pull request merged**
